%% specify path to libraries
nngdir = 'C:\Program Files (x86)\nng';

%% build
p = simulinkproject;
olddir = cd(fullfile(p.RootFolder,'lib','comms'));

disp('## Building sfun_sub');
mex( '-g',...
    ['-I' fullfile(p.RootFolder,'lib','comms','include')],...
    ['-I' fullfile(nngdir,'include','nng')],...
    ['-L' fullfile(nngdir,'lib')],...
    '-lnng',...
    fullfile('src','sfun_sub.c'));

disp('## Building sfun_pub');
mex( '-g',...
    ['-I' fullfile(p.RootFolder,'lib','comms','include')],...
    ['-I' fullfile(nngdir,'include','nng')],...
    ['-L' fullfile(nngdir,'lib')],...
    '-lnng',...
    fullfile('src','sfun_pub.c'));

cd(olddir);