function makecfg(info)

p = simulinkproject;
nngdir = fullfile(p.RootFolder, 'nng');
disp(['Running makecfg from folder: ',pwd]);

addIncludePaths(info, { ...
    fullfile(p.RootFolder,'lib','comms','include') ...
    fullfile(nngdir, 'include') ...
    });

%addSourceFiles(info, 'libnng.a', fullfile(pwd, 'include'));
% addLinkObjects(info, ...
%     'libnng.a', ...
%     fullfile(pwd, 'include'), ...
%     1000, false, true);
addLinkFlags(info, '-L/usr/local/lib -lnng');
end
